;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ability.Movmenet.Normal.Dash",NewTagName="Ability.Movement.Normal.Dash")
+GameplayTagRedirects=(OldTagName="Ability.Movmenet.Normal",NewTagName="Ability.Movement.Normal")
+GameplayTagRedirects=(OldTagName="Ability.Movmenet",NewTagName="Ability.Movement")
+GameplayTagRedirects=(OldTagName="State.Stunned",NewTagName="State.Staggered")
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Slash",DevComment="")
+GameplayTagList=(Tag="Ability.Block",DevComment="")
+GameplayTagList=(Tag="Ability.Movement.LockOn.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Movement.Normal.Dash",DevComment="")
+GameplayTagList=(Tag="Camera Shake",DevComment="")
+GameplayTagList=(Tag="CameraShake",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Damage.Direct",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.HitReact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Enemy.Hit.CameraShake",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Blocked",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.CameraShake",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.State.Poisoned",DevComment="")
+GameplayTagList=(Tag="Shake",DevComment="")
+GameplayTagList=(Tag="State",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Blocking",DevComment="")
+GameplayTagList=(Tag="State.LockedOn",DevComment="")
+GameplayTagList=(Tag="State.Parryable",DevComment="")
+GameplayTagList=(Tag="State.Parrying",DevComment="")
+GameplayTagList=(Tag="State.Poisoned",DevComment="")
+GameplayTagList=(Tag="State.Staggered",DevComment="")
+GameplayTagList=(Tag="State.Strafing",DevComment="")

